name: Storage and Stuff
url: https://evancs.com
description: Blogs and reposts about computer storage, programming, and other topics.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
